services:
  redis:
    image: docker.io/library/redis:${REDIS_VERSION:-latest}
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./mount/${REDIS_VERSION:-latest}:/data:Z
    command: [ "redis-server", "--appendonly", "yes" ]

  redisinsight:
    image: docker.io/redis/redisinsight:${REDIS_INS_VERSION:-latest}
    container_name: redis-insight
    restart: always
    environment:
      # Automatically connect to the 'redis' service on start
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_ALIAS=redis-server
    ports:
      - "5540:5540"
    volumes:
      - ./mount/${REDIS_INS_VERSION:-latest}:/data:Z
    depends_on:
      - redis
